# Generated by Django 5.0 on 2026-02-12 22:30

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cities_light', '0012_city_translations_country_translations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grad_year', models.PositiveIntegerField()),
                ('school_name', models.CharField(max_length=63)),
                ('degree', models.CharField(choices=[('HIGHSCHOOL', 'High School'), ('CERTIFICATE', 'Certificate'), ('ASSOCIATES', "Associate's"), ('BACHELORS', "Bachelor's"), ('MASTERS', "Master's"), ('DOCTORATE', 'Doctorate')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True)),
                ('current_employee', models.BooleanField(default=False)),
                ('company_name', models.CharField(max_length=31)),
                ('position_title', models.CharField(max_length=31)),
                ('job_description', models.TextField(max_length=511)),
            ],
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company', models.TextField(max_length=63)),
                ('links', models.TextField(help_text='Please enter links as Comma Separated Values', max_length=127)),
                ('headline', models.TextField(max_length=1023)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('links', models.TextField(help_text='Please enter links as Comma Separated Values', max_length=127)),
                ('headline', models.TextField(max_length=1023)),
                ('city', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.city')),
                ('country', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.country')),
                ('education', models.ManyToManyField(to='profiles.education')),
                ('experience', models.ManyToManyField(to='profiles.experience')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
