# Generated by Django 5.0 on 2026-02-10 19:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0012_city_translations_country_translations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=31)),
                ('last_name', models.CharField(max_length=31)),
                ('email', models.EmailField(max_length=127)),
                ('username', models.SlugField(default='<django.db.models.fields.CharField>-<django.db.models.fields.CharField>-<django.db.models.fields.AutoField>', max_length=127, unique=True)),
                ('pfp', models.ImageField(upload_to=None)),
                ('city', models.ManyToManyField(blank=True, to='cities_light.city')),
                ('country', models.ManyToManyField(blank=True, to='cities_light.country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('ttuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profiles.ttuser')),
                ('headline', models.TextField(max_length=1023)),
            ],
            options={
                'abstract': False,
            },
            bases=('profiles.ttuser',),
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('ttuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profiles.ttuser')),
            ],
            options={
                'abstract': False,
            },
            bases=('profiles.ttuser',),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('current_employee', models.BooleanField(default=False)),
                ('company_name', models.CharField(max_length=31)),
                ('position_title', models.CharField(max_length=31)),
                ('job_description', models.TextField(max_length=511)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.ttuser')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grad_year', models.PositiveIntegerField()),
                ('school_name', models.CharField(max_length=63)),
                ('degree', models.CharField(choices=[('HIGHSCHOOL', 'Highschool'), ('CERTIFICATE', 'Certificate'), ('ASSOCIATES', 'Associates'), ('BACHELORS', 'Bachelors'), ('MASTERS', 'Masters'), ('DOCTORATE', 'Doctorate')], max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.ttuser')),
            ],
        ),
    ]
