# Generated by Django 5.0 on 2026-02-10 20:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ttuser',
            options={'verbose_name': 'Talent Trek User', 'verbose_name_plural': 'Talent Trek Users'},
        ),
        migrations.RemoveField(
            model_name='ttuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='ttuser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='ttuser',
            name='username',
        ),
        migrations.AddField(
            model_name='ttuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='ttuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='ttuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='ttuser',
            name='link',
            field=models.GeneratedField(db_persist=False, expression='<django.db.models.fields.CharField>-<django.db.models.fields.CharField>-<django.db.models.fields.AutoField>', output_field=models.CharField(max_length=127), unique=True),
        ),
        migrations.AlterField(
            model_name='ttuser',
            name='email',
            field=models.EmailField(max_length=127, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='ttuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=31, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='ttuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=31, verbose_name='last_name'),
        ),
    ]
