# Generated by Django 5.0 on 2026-02-10 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0012_city_translations_country_translations_and_more'),
        ('profiles', '0003_alter_education_user_alter_ttuser_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttuser',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cities_light.city'),
        ),
        migrations.AddField(
            model_name='ttuser',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cities_light.country'),
        ),
        migrations.AddField(
            model_name='ttuser',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cities_light.region'),
        ),
    ]
