# Generated by Django 5.0 on 2026-02-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='posts', to='skills.skill'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='post_images/default_job_posting.jpg', upload_to='post_images/'),
        ),
    ]
