# Generated by Django 5.0 on 2026-03-11 08:57

import posting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='post_images/default_job_posting.jpg', upload_to=posting.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='query',
            name='education_level',
            field=models.CharField(blank=True, max_length=15, verbose_name=[('HIGHSCHOOL', 'High School'), ('CERTIFICATE', 'Certificate'), ('ASSOCIATES', "Associate's"), ('BACHELORS', "Bachelor's"), ('MASTERS', "Master's"), ('DOCTORATE', 'Doctorate')]),
        ),
    ]
