# Generated by Django 5.0 on 2026-02-19 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='post_images/default_job_posting.jpg', upload_to='post_images/'),
        ),
    ]
