# Generated by Django 5.0 on 2026-03-11 23:07

import posting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_post_latitude_post_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='post_images/default_job_posting.jpg', upload_to=posting.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
