# Generated by Django 5.0 on 2026-03-12 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_alter_post_image_alter_query_education_level'),
        ('posting', '0003_alter_post_image_alter_post_latitude_and_more'),
    ]

    operations = [
    ]
