# Generated by Django 5.0 on 2026-03-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0004_merge_20260312_0447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='query',
            name='posting',
        ),
    ]
