# Generated by Django 5.0 on 2026-02-19 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0004_remove_post_location_post_city_post_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='region',
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='state',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='street',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='city',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='country',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
