# Generated by Django 5.0 on 2026-02-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0005_remove_post_region_post_location_post_postal_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='job_type',
            field=models.CharField(choices=[('FT', 'Full-time'), ('PT', 'Part-time'), ('CT', 'Contract'), ('IN', 'Internship'), ('TP', 'Temporary'), ('OT', 'Other')], default='FT', max_length=2),
        ),
        migrations.AddField(
            model_name='post',
            name='location_type',
            field=models.CharField(choices=[('ON', 'On-site'), ('HY', 'Hybrid'), ('RE', 'Remote')], default='ON', max_length=2),
        ),
    ]
