# Generated by Django 5.0 on 2026-02-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0006_post_job_type_post_location_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visa_sponsorship',
            field=models.BooleanField(default=False),
        ),
    ]
