# Generated by Django 5.0 on 2026-02-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0007_post_visa_sponsorship'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='salary_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='salary_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
