# Generated by Django 5.0 on 2026-02-19 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('posting', '0008_post_salary_max_post_salary_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='recruiter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.recruiter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='company_name',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
