# Generated by Django 5.0 on 2026-02-19 23:00

import accounts.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cities_light', '0012_city_translations_country_translations_and_more'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=31, verbose_name='first name')),
                ('last_name', models.CharField(max_length=31, verbose_name='last_name')),
                ('email', models.EmailField(max_length=127, unique=True, verbose_name='email address')),
                ('link', models.SlugField(blank=True, max_length=255)),
                ('pfp', models.ImageField(blank=True, upload_to=accounts.models.get_pfp_path)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('headline', models.TextField(blank=True, max_length=1023)),
                ('is_seeker', models.BooleanField(default=False)),
                ('is_recruiter', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cities_light.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cities_light.country')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cities_light.region')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Talent Trek User',
                'verbose_name_plural': 'Talent Trek Users',
                'db_table': 'auth_user',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grad_year', models.PositiveIntegerField()),
                ('school_name', models.CharField(max_length=63)),
                ('degree', models.CharField(choices=[('HIGHSCHOOL', 'High School'), ('CERTIFICATE', 'Certificate'), ('ASSOCIATES', "Associate's"), ('BACHELORS', "Bachelor's"), ('MASTERS', "Master's"), ('DOCTORATE', 'Doctorate')], max_length=15)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('current_employee', models.BooleanField(default=False)),
                ('company_name', models.CharField(max_length=63)),
                ('position_title', models.CharField(max_length=63)),
                ('job_description', models.TextField(max_length=511)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company', models.TextField(max_length=63)),
                ('links', models.TextField(blank=True, help_text='Please enter links as Comma Separated Values', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('links', models.TextField(help_text='Please enter links as Comma Separated Values', max_length=255)),
                ('resume', models.FileField(blank=True, upload_to=accounts.models.get_resume_path)),
                ('education_is_hidden', models.BooleanField(default=False)),
                ('experience_is_hidden', models.BooleanField(default=False)),
                ('links_is_hidden', models.BooleanField(default=False)),
                ('account_is_hidden', models.BooleanField(default=False)),
                ('education', models.ManyToManyField(blank=True, to='accounts.education')),
                ('experience', models.ManyToManyField(blank=True, to='accounts.experience')),
                ('skills', models.ManyToManyField(blank=True, to='skills.skill')),
            ],
            options={
                'verbose_name': 'Job Seeker',
            },
        ),
    ]
