# Generated by Django 5.0 on 2026-02-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttuser',
            name='link',
            field=models.SlugField(blank=True, max_length=127),
        ),
    ]
