# Generated by Django 5.0 on 2026-02-17 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experience',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='account_is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='education',
            field=models.ManyToManyField(blank=True, to='accounts.education'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='experience',
            field=models.ManyToManyField(blank=True, to='accounts.experience'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='links',
            field=models.TextField(blank=True, help_text='Please enter links as Comma Separated Values', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='resume',
            field=models.FileField(blank=True, upload_to='resumes/'),
        ),
    ]
