# Generated by Django 5.0 on 2026-02-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttuser',
            name='is_recruiter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ttuser',
            name='is_seeker',
            field=models.BooleanField(default=False),
        ),
    ]
