# Generated by Django 5.0 on 2026-02-19 02:20

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='education',
            field=models.ManyToManyField(blank=True, to='accounts.education'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='experience',
            field=models.ManyToManyField(blank=True, to='accounts.experience'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='resume',
            field=models.FileField(blank=True, upload_to=accounts.models.get_resume_path),
        ),
    ]
