# Generated by Django 5.0 on 2026-02-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='degree_name',
            field=models.CharField(blank=True, max_length=63),
        ),
    ]
