# Generated by Django 5.0 on 2026-02-10 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_ttuser_options_remove_ttuser_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.jobseeker'),
        ),
        migrations.AlterField(
            model_name='ttuser',
            name='link',
            field=models.SlugField(max_length=127, unique=True),
        ),
    ]
