# Generated by Django 5.0 on 2026-02-21 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_education_degree_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='job_description',
            field=models.TextField(blank=True, max_length=511),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='links',
            field=models.TextField(blank=True, help_text='Please enter links as Comma Separated Values', max_length=255),
        ),
    ]
