# Generated by Django 5.0 on 2026-02-17 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_education_is_hidden_experience_is_hidden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='links_is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
