# Generated by Django 5.0 on 2026-02-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_jobseeker_education_alter_jobseeker_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='is_hidden',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='is_hidden',
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='education_is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='experience_is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
