# Generated by Django 5.0 on 2026-03-11 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_experience_job_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ttuser',
            name='link',
        ),
    ]
