# Generated by Django 5.0 on 2026-02-17 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_jobseeker_links_is_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='links',
            field=models.TextField(help_text='Please enter links as Comma Separated Values', max_length=255),
        ),
    ]
