# Generated by Django 5.0 on 2026-02-13 10:14

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_ttuser_city_alter_ttuser_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttuser',
            name='pfp',
            field=models.ImageField(blank=True, upload_to=accounts.models.get_pfp_path),
        ),
    ]
