# Generated by Django 5.0 on 2026-02-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_recruiter_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='company_name',
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='position_title',
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='links',
            field=models.TextField(blank=True, help_text='Please enter links as Comma Separated Values', max_length=255),
        ),
        migrations.AlterField(
            model_name='ttuser',
            name='link',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
