# Generated by Django 5.0 on 2026-03-12 23:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_ttuser_link_remove_ttuser_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttuser',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last activity'),
        ),
        migrations.AddField(
            model_name='ttuser',
            name='logins',
            field=models.IntegerField(default=0),
        ),
    ]
