# Generated by Django 5.0 on 2026-03-12 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_ttuser_last_activity_ttuser_logins'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttuser',
            name='average_time_online',
            field=models.TimeField(blank=True, null=True, verbose_name='average_time_online'),
        ),
    ]
