# Generated by Django 5.0 on 2026-03-13 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_ttuser_average_time_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ttuser',
            name='average_time_online',
        ),
        migrations.RemoveField(
            model_name='ttuser',
            name='last_activity',
        ),
    ]
