# Generated by Xavier Evans GPT-67 on 2026-03-3 Late o'clock

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('applications', '0001_initial'),
        ('posting', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ttuser')),
                ('message', models.CharField(max_length=1023)),
                ('image', models.ImageField(blank=True, height_field=None, width_field=None)),
                ('viewslink', models.CharField(blank=True, max_length=31)),
                ('read', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True, blank=True)),
            ],
        ),
    ]