# Generated by Django 5.0 on 2026-02-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('JavaScript', 'JavaScript'), ('TypeScript', 'TypeScript'), ('Ruby', 'Ruby'), ('PHP', 'PHP'), ('C#', 'C#'), ('Go', 'Go'), ('Rust', 'Rust'), ('Swift', 'Swift'), ('Kotlin', 'Kotlin'), ('Scala', 'Scala'), ('Perl', 'Perl'), ('Lua', 'Lua'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('React', 'React'), ('Vue.js', 'Vue.js'), ('Angular', 'Angular'), ('Svelte', 'Svelte'), ('Next.js', 'Next.js'), ('Gatsby', 'Gatsby'), ('Redux', 'Redux'), ('jQuery', 'jQuery'), ('Node.js', 'Node.js'), ('Express', 'Express'), ('Django', 'Django'), ('Flask', 'Flask'), ('Spring Boot', 'Spring Boot'), ('ASP.NET Core', 'ASP.NET Core'), ('Ruby on Rails', 'Ruby on Rails'), ('Symfony', 'Symfony'), ('Laravel', 'Laravel'), ('GraphQL', 'GraphQL'), ('SQL', 'SQL'), ('MySQL', 'MySQL'), ('PostgreSQL', 'PostgreSQL'), ('MongoDB', 'MongoDB'), ('Redis', 'Redis'), ('Cassandra', 'Cassandra'), ('SQLite', 'SQLite'), ('Oracle', 'Oracle'), ('Firebase', 'Firebase'), ('AWS', 'AWS'), ('Azure', 'Azure'), ('GCP', 'GCP'), ('Docker', 'Docker'), ('Kubernetes', 'Kubernetes'), ('Terraform', 'Terraform'), ('Jenkins', 'Jenkins'), ('GitLab CI', 'GitLab CI'), ('CI/CD', 'CI/CD'), ('Ansible', 'Ansible'), ('Vagrant', 'Vagrant'), ('PyTorch', 'PyTorch'), ('TensorFlow', 'TensorFlow'), ('scikit-learn', 'scikit-learn'), ('NumPy', 'NumPy'), ('pandas', 'pandas'), ('Matplotlib', 'Matplotlib'), ('Seaborn', 'Seaborn'), ('SQLAlchemy', 'SQLAlchemy'), ('Kafka', 'Kafka'), ('Scrum', 'Scrum'), ('Agile', 'Agile'), ('SAFe', 'SAFe'), ('Kanban', 'Kanban'), ('XP', 'XP'), ('TDD', 'TDD'), ('Canva', 'Canva'), ('Photoshop', 'Photoshop'), ('Illustrator', 'Illustrator'), ('InDesign', 'InDesign'), ('Premiere Pro', 'Premiere Pro'), ('After Effects', 'After Effects'), ('Audition', 'Audition'), ('Lightroom', 'Lightroom'), ('Adobe XD', 'Adobe XD'), ('Figma', 'Figma'), ('Balsamiq', 'Balsamiq'), ('Selenium', 'Selenium'), ('Appium', 'Appium'), ('Jest', 'Jest'), ('pytest', 'pytest'), ('Cucumber', 'Cucumber'), ('Postman', 'Postman'), ('REST API', 'REST API'), ('SOAP', 'SOAP'), ('MQTT', 'MQTT'), ('WebSockets', 'WebSockets')], help_text='Select the skill', max_length=100, unique=True)),
            ],
        ),
    ]
