# Generated by Django 5.0 on 2026-02-12 21:15

from django.db import migrations

from enums.skills import Skills


def populate_skills(apps, schema_editor):
    Skill = apps.get_model('skills', 'Skill')
    for skill in Skills:
        Skill.objects.get_or_create(name=skill.value)


def reverse_populate_skills(apps, schema_editor):
    Skill = apps.get_model('skills', 'Skill')
    Skill.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_skills, reverse_populate_skills),
    ]
